"""empty message

Revision ID: 2215ddb87985
Revises: 9a00a8159209
Create Date: 2023-12-20 20:07:44.052094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2215ddb87985'
down_revision: Union[str, None] = '9a00a8159209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_answers', sa.Column('question_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_answers', 'question_id')
    # ### end Alembic commands ###
